#!/usr/bin/env bash
# claude-myactivity — first-run setup. Pure bash, no Claude needed.
# Asks a few preferences and writes them to ./myactivity.config (git-ignored).
# Re-run anytime to change them.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$SCRIPT_DIR/myactivity.config"

echo "claude-myactivity setup"
echo "─────────────────────────"

# Load current values (if re-running) so prompts show existing answers as defaults.
TICKET_ENABLED="false"; TICKET_PREFIX=""; WIN_W="1100"; WIN_H="700"; WIN_MARGIN="40"
[ -f "$CONFIG" ] && . "$CONFIG"

# --- dependency check (warn, don't block) ---
missing=""
for dep in claude jq uuidgen sed find osascript; do
  command -v "$dep" >/dev/null 2>&1 || missing="$missing $dep"
done
[ -n "$missing" ] && echo "⚠ missing tools:$missing (install before using)"

ask() { # ask "<prompt>" "<default>" -> echoes the answer
  local prompt="$1" def="$2" ans
  read -r -p "$prompt [$def]: " ans || true   # EOF (non-interactive) -> default
  echo "${ans:-$def}"
}

# --- ticket convention ---
tdef="N"; [ "$TICKET_ENABLED" = "true" ] && tdef="Y"
ans="$(ask "Prefix folder names with a ticket key when a session is about a ticket? (y/N)" "$tdef")"
case "$ans" in
  [yY]*) TICKET_ENABLED="true"
         TICKET_PREFIX="$(ask "  Ticket prefix / board (e.g. ACME, JIRA)" "${TICKET_PREFIX:-}")" ;;
  *)     TICKET_ENABLED="false"; TICKET_PREFIX="" ;;
esac

# --- iTerm window geometry ---
WIN_W="$(ask "iTerm window width (px)" "$WIN_W")"
WIN_H="$(ask "iTerm window height (px)" "$WIN_H")"
WIN_MARGIN="$(ask "iTerm top margin (px)" "$WIN_MARGIN")"

# --- write config ---
cat > "$CONFIG" <<EOF
# claude-myactivity preferences (generated by setup.sh). Edit or re-run setup.sh.
TICKET_ENABLED=$TICKET_ENABLED
TICKET_PREFIX=$TICKET_PREFIX
WIN_W=$WIN_W
WIN_H=$WIN_H
WIN_MARGIN=$WIN_MARGIN
EOF
echo "✓ wrote ${CONFIG#"$SCRIPT_DIR"/}"

# --- offer to launch ---
ans="$(ask "Open Claude now in this folder? (y/N)" "N")"
case "$ans" in
  [yY]*) exec "$SCRIPT_DIR/new.sh" ;;
  *)     echo "Done. Start anytime with:  ./new.sh   (or just: claude)" ;;
esac
